//
//  ScreenDeckSmokeTests+Screens.swift
//  DialedInUITests
//
//  Generated by scripts/gen-smoke-tests.sh from AppViewForUITesting.swift. Do not edit.
//

import XCTest

extension ScreenDeckSmokeTests {

    func testCreateExercise() { smoke("STARTSCREEN_CREATE_EXERCISE") }

    func testCreateWorkout() { smoke("STARTSCREEN_CREATE_WORKOUT") }

    func testCreateProgram() { smoke("STARTSCREEN_CREATE_PROGRAM") }

    func testSocialProfile() { smoke("STARTSCREEN_SOCIAL_PROFILE") }

    func testComments() { smoke("STARTSCREEN_COMMENTS") }

    func testOwnProfile() { smoke("STARTSCREEN_OWN_PROFILE") }

    func testNotifications() { smoke("STARTSCREEN_NOTIFICATIONS") }

    func testNotificationSettings() { smoke("STARTSCREEN_NOTIFICATION_SETTINGS") }

    func testUsername() { smoke("STARTSCREEN_USERNAME") }

    func testSharedItem() { smoke("STARTSCREEN_SHARED_ITEM") }

    func testShareCard() { smoke("STARTSCREEN_SHARE_CARD") }

    func testToday() { smoke("STARTSCREEN_TODAY") }

    func testSocial() { smoke("STARTSCREEN_SOCIAL") }

    func testTraining() { smoke("STARTSCREEN_TRAINING") }

    func testWorkoutTracker() { smoke("STARTSCREEN_WORKOUT_TRACKER") }

    func testTemplateDetail() { smoke("STARTSCREEN_TEMPLATE_DETAIL") }

    func testProgramLibrary() { smoke("STARTSCREEN_PROGRAM_LIBRARY") }

    func testWorkouts() { smoke("STARTSCREEN_WORKOUTS") }

    func testMusclePicker() { smoke("STARTSCREEN_MUSCLE_PICKER") }

    func testActiveProgram() { smoke("STARTSCREEN_ACTIVE_PROGRAM") }

    func testExerciseDetail() { smoke("STARTSCREEN_EXERCISE_DETAIL") }

    func testExercises() { smoke("STARTSCREEN_EXERCISES") }

    func testWorkoutHistory() { smoke("STARTSCREEN_WORKOUT_HISTORY") }

    func testSessionDetail() { smoke("STARTSCREEN_SESSION_DETAIL") }

    func testGymProfiles() { smoke("STARTSCREEN_GYM_PROFILES") }

    func testNutrition() { smoke("STARTSCREEN_NUTRITION") }

    func testMealDetail() { smoke("STARTSCREEN_MEAL_DETAIL") }

    func testRecipes() { smoke("STARTSCREEN_RECIPES") }

    func testRecipeDetail() { smoke("STARTSCREEN_RECIPE_DETAIL") }

    func testFoods() { smoke("STARTSCREEN_FOODS") }

    func testFoodDetail() { smoke("STARTSCREEN_FOOD_DETAIL") }

    func testCreateFood() { smoke("STARTSCREEN_CREATE_FOOD") }

    func testMealDescribe() { smoke("STARTSCREEN_MEAL_DESCRIBE") }

    func testNutritionLibraryPicker() { smoke("STARTSCREEN_NUTRITION_LIBRARY_PICKER") }

    func testAnalytics() { smoke("STARTSCREEN_ANALYTICS") }

    func testBodyMetrics() { smoke("STARTSCREEN_BODY_METRICS") }

    func testScaleWeight() { smoke("STARTSCREEN_SCALE_WEIGHT") }

    func testMeasurementDetail() { smoke("STARTSCREEN_MEASUREMENT_DETAIL") }

    func testLogWeight() { smoke("STARTSCREEN_LOG_WEIGHT") }

    func testLogMeasurement() { smoke("STARTSCREEN_LOG_MEASUREMENT") }

    func testNutritionAnalytics() { smoke("STARTSCREEN_NUTRITION_ANALYTICS") }

    func testProfile() { smoke("STARTSCREEN_PROFILE") }

    func testAccount() { smoke("STARTSCREEN_ACCOUNT") }

    func testDeleteAccount() { smoke("STARTSCREEN_DELETE_ACCOUNT") }

    func testSiri() { smoke("STARTSCREEN_SIRI") }

    func testWhySubscribe() { smoke("STARTSCREEN_WHY_SUBSCRIBE") }

    func testPaywall() { smoke("STARTSCREEN_PAYWALL") }

    func testFollowers() { smoke("STARTSCREEN_FOLLOWERS") }

    func testInvite() { smoke("STARTSCREEN_INVITE") }

    func testSetKeyboard() { smoke("STARTSCREEN_SET_KEYBOARD") }

    func testWeeklyReview() { smoke("STARTSCREEN_WEEKLY_REVIEW") }

    func testMuscleBalance() { smoke("STARTSCREEN_MUSCLE_BALANCE") }

    func testChallengeDetail() { smoke("STARTSCREEN_CHALLENGE_DETAIL") }

    func testChallenges() { smoke("STARTSCREEN_CHALLENGES") }

    func testProgressPhotos() { smoke("STARTSCREEN_PROGRESS_PHOTOS") }
}
